<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[About to begin executing Suite Suite]]>
    </line>
    <line>
      <![CDATA[About to begin executing Test Test]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : LoginTest.Setup]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : LoginTest.Setup]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : LoginTest.loginToDummyTest]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : LoginTest.loginToDummyTest]]>
    </line>
    <line>
      <![CDATA[<a href=ScreenCapture/loginToDummyTest_20-12-2014_13-58-407.png><img src=ScreenCapture/loginToDummyTest_20-12-2014_13-58-407.png alt=""height='100' width='100'/> <br />]]>
    </line>
    <line>
      <![CDATA[Test Method resides in com.uiautomation.testscripts.LoginTest]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : LoginTest.tearDown]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : LoginTest.tearDown]]>
    </line>
    <line>
      <![CDATA[Completed executing test Test]]>
    </line>
    <line>
      <![CDATA[About to end executing Suite Suite]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="65665" started-at="2014-12-20T08:03:58Z" finished-at="2014-12-20T08:05:04Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="65665" started-at="2014-12-20T08:03:58Z" finished-at="2014-12-20T08:05:04Z">
      <class name="com.uiautomation.testscripts.LoginTest">
        <test-method status="PASS" signature="Setup()[pri:0, instance:com.uiautomation.testscripts.LoginTest@11a0d8b]" name="Setup" is-config="true" duration-ms="48411" started-at="2014-12-20T13:33:58Z" finished-at="2014-12-20T13:34:47Z">
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : LoginTest.Setup]]>
            </line>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method status="FAIL" signature="loginToDummyTest()[pri:0, instance:com.uiautomation.testscripts.LoginTest@11a0d8b]" name="loginToDummyTest" duration-ms="10858" started-at="2014-12-20T13:34:47Z" description="Login to dummy site " finished-at="2014-12-20T13:34:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [barawar] but found [billu]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [barawar] but found [billu]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.uiautomation.testscripts.LoginTest.loginToDummyTest(LoginTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : LoginTest.loginToDummyTest]]>
            </line>
            <line>
              <![CDATA[<a href=ScreenCapture/loginToDummyTest_20-12-2014_13-58-407.png><img src=ScreenCapture/loginToDummyTest_20-12-2014_13-58-407.png alt=""height='100' width='100'/> <br />]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginToDummyTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.uiautomation.testscripts.LoginTest@11a0d8b]" name="tearDown" is-config="true" duration-ms="0" started-at="2014-12-20T13:35:04Z" finished-at="2014-12-20T13:35:04Z">
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : LoginTest.tearDown]]>
            </line>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.uiautomation.testscripts.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
